### ISSUE TITLE
 UNet: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid

### ISSUE THREAD

**Issue by YSUN-coder** [wang-xinyu/tensorrtx#1089]
## Env

- GPU, Jetson Nano L4T 32.7.2
- OS, Ubuntu18.04
- Cuda version 10.2
- TensorRT version 8.2.1.8-1+cuda10.2
- OpenCV 4.5
- CMake 3.18

## About this repo

- [a772e46](https://github.com/wang-xinyu/tensorrtx/commit/a772e4618882893b4886c821c98846dfd3d7795e)
- UNet

## Your problem

- what is your command? `unet -s`, after changed the hardcode .wts path.
- To get the .wts, I did a change in gen_wts.py:
```    
   # New version
    #net = UNet(n_channels=3, n_classes=2, bilinear=False)
    #net.load_state_dict(torch.load('unet_carvana_scale1_epoch2.pth'))

    # Old version
    net = torch.load('unet_carvana_scale0.5_epoch2.pth')
```
- To [Looser throw specifier for ‘virtual void Logger::log’](https://forums.developer.nvidia.com/t/looser-throw-specifier-for-virtual-void-logger-log/187963) about trt 8, I got some warning while `make`. 
- I am using the pretrained model from https://github.com/milesial/Pytorch-UNet/releases/tag/v3.0
- what's your output?
```
[08/30/2022-17:23:47] [E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[08/30/2022-17:23:47] [E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[08/30/2022-17:23:47] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
set name out
Building engine, please wait for a while...
[08/30/2022-17:23:47] [E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[08/30/2022-17:23:47] [E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[08/30/2022-17:23:47] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[08/30/2022-17:23:47] [E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)
Build engine successfully!
unet: /home/nano/mojowrepo/tensorrtx/unet/unet.cpp:192: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)
```
I am not sure what caused the issue, like tensorrt8, Jetson Nano limits, or something else.

- what output do you expect?
Is there anyone who make it successfully and get the inference speed in Jetson Nano?

**Comment by wang-xinyu** [comment]
This error is not related to trt8.  It's the model mismatch.

**Comment by YSUN-coder** [comment]
> This error is not related to trt8. It's the model mismatch.

I generate .wts file with gen_wts.py. My input was a checkpoint.pth. It throw a error : .
```
Traceback (most recent call last):
  File "gen_wts.py", line 42, in <module>
    main()
  File "gen_wts.py", line 16, in main
    net = net.to('cuda:0')
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

```

Then, I changed the load model code for loading checkpoint. The `UNet` class was imported from  https://github.com/newfarms/unet/blob/feature-mojow-rock-segmentation-review-sylvia/unet/unet_model.py.

 ```
    net = UNet(n_channels=3, n_classes=2, bilinear=False)
    net.load_state_dict(torch.load('checkpoints/checkpoint_epoch75.pth'))
    net = net.to('cuda:0')
    net = net.eval()
```

After this, I could get a  .wts  file. Did this cause the model to mismatch?

**Comment by YSUN-coder** [comment]
I also tried the pretrainined model from Pytorch-UNet: [[unet_carvana_scale0.5_epoch2.pth](https://github.com/milesial/Pytorch-UNet/releases/download/v3.0/unet_carvana_scale0.5_epoch2.pth)](https://github.com/milesial/Pytorch-UNet/releases/tag/v3.0)

The error is as follows:

[08/31/2022-14:38:46] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
set name out
Building engine, please wait for a while...
[08/31/2022-14:38:46] [E] [TRT] 3: (Unnamed Layer* 28) [Convolution]:kernel weights has count 4718592 but 2359296 was expected
[08/31/2022-14:38:46] [E] [TRT] 4: (Unnamed Layer* 28) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 512 input channels, 512 output channels and 1 groups were specified. Expected Weights count is 512 * 3*3 * 512 / 1 = 2359296
[08/31/2022-14:38:46] [E] [TRT] 4: [convolutionNode.cpp::computeOutputExtents::39] Error Code 4: Internal Error ((Unnamed Layer* 28) [Convolution]: number of kernel weights does not match tensor dimensions)
[08/31/2022-14:38:46] [E] [TRT] 4: [network.cpp::validate::2835] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)
Build engine successfully!
unet: /home/nano/mojowrepo/tensorrtx/unet/unet.cpp:196: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
Can you try the v1.0 of Pytorch-UNet?

**Comment by YSUN-coder** [comment]
I  checked out the pytorch-unet v1.0 tag as the below:

$ git checkout v1.0

and used [unet_carvana_scale1_epoch5.pth](https://github.com/milesial/Pytorch-UNet/releases/download/v1.0/unet_carvana_scale1_epoch5.pth) in https://github.com/milesial/Pytorch-UNet/releases/tag/v1.0

However, the current version gen_wts.py doesn't work with the model.

Could you help to update the gen_wts.py? I tried several ways to update it but none of them worked with the c++ unet.cpp.

Thanks in advance. @wang-xinyu

**Comment by YSUN-coder** [comment]
```
nano@nano:~/mojowrepo/unet-tensorrt/build$ ./unet -s
Loading weights: /home/nano/mojowrepo/unet-tensorrt/unet_v1_scale1_class1_bilinear.wts
set name out
Building engine, please wait for a while...
[08/31/2022-23:33:16] [W] [TRT] Tactic Device request: 2024MB Available: 1959MB. Device memory is insufficient to use tactic.
[08/31/2022-23:33:16] [W] [TRT] Skipping tactic 0 due to insuficient memory on requested size of 2024 detected for tactic 1002.
[08/31/2022-23:33:16] [W] [TRT] Tactic Device request: 2024MB Available: 1954MB. Device memory is insufficient to use tactic.
[08/31/2022-23:33:16] [W] [TRT] Skipping tactic 1 due to insuficient memory on requested size of 2024 detected for tactic 0.
[08/31/2022-23:33:16] [W] [TRT] Tactic Device request: 2024MB Available: 1954MB. Device memory is insufficient to use tactic.
[08/31/2022-23:33:16] [W] [TRT] Skipping tactic 0 due to insuficient memory on requested size of 2024 detected for tactic 1002.
[08/31/2022-23:33:16] [W] [TRT] Tactic Device request: 2024MB Available: 1954MB. Device memory is insufficient to use tactic.
[08/31/2022-23:33:16] [W] [TRT] Skipping tactic 1 due to insuficient memory on requested size of 2024 detected for tactic 0.
[08/31/2022-23:43:10] [E] [TRT] 1: [resizingAllocator.cpp::deallocate::100] Error Code 1: Cuda Runtime (the launch timed out and was terminated)
[08/31/2022-23:43:10] [W] [TRT] GPU error during getBestTactic: (Unnamed Layer* 20) [Pooling] : the launch timed out and was terminated
[08/31/2022-23:43:10] [E] [TRT] 1: [resizingAllocator.cpp::deallocate::100] Error Code 1: Cuda Runtime (the launch timed out and was terminated)
[08/31/2022-23:43:10] [E] [TRT] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node (Unnamed Layer* 20) [Pooling].)
Build engine successfully!
unet: /home/nano/mojowrepo/unet-tensorrt/unet.cpp:216: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)
```
