### ISSUE TITLE
IndexError: list index out of range in v7.0

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [wang-xinyu/tensorrtx#1186]
## Env

- GPU: Orin.
- OS: Ubuntu 20.04.
- Cuda version (using NVIDIA container): nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
- TensorRT version: tensorrt            8.4.0.11

## About this repo

- which branch/tag/commit are you using? 7.0
- which model? yolov5, retinaface? yolov5n

## Your problem

- what is your command? `python3 yolov5_det_trt.py`
- what's your output?
```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov5_det_trt.py", line 383, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image(self.image_path_batch))
  File "yolov5_det_trt.py", line 178, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov5_det_trt.py", line 383, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image(self.image_path_batch))
  File "yolov5_det_trt.py", line 178, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
```

- what output do you expect?
All the conversion process works fine. The models are the original from Yolov5 (I have not used custom dataset). If I launch:
`./yolov5_det -d yolov5n.engine ../samples`
I do not get any problem.

**Comment by wang-xinyu** [comment]
Yes, I have updated the yolov5-v7.0 tag just now.
