### ISSUE TITLE
SuperPoint test with tensor size mismatch error when using `supernet.engine`

### ISSUE THREAD

**Issue by myboyhood** [wang-xinyu/tensorrtx#1215]
## Env

- GPU: GTX1650.
- OS: Ubuntu18.04.
- Cuda version 10.2 cudnn 8.2.0
- TensorRT 7.1.3.4

## About this repo

- branch: master
- model: superpoint

## Problem
I want to test an image with loading and init the `supernet.engine` which is produced by 
`./supernet -s SuperPointPretrainedNetwork/superpoint_v1.wts` 
I write a test code which is shown below later.
**The problem**  When I verify the tensor of `semi` size, its size is not matched. And get error `Tensor volumes dont match between cfg and engine file`

## My condition
When the image is `160 *120` , when I load the engine. I add `prinft` to see the dims of input and output.
The three inputDims multiplied is 19500 = 65 * 15 * 20, but the OutputTensors of `semi` which `tensor.volume` = 19200 (I guess 64 * 15 *20)
I also check the input and output of `desc`, which is right.
The three inputDims multiplied is 256 * 15 * 20 = 76800, and I see the same size of OutputTensors `tensor.volume` = 76800

I do not know which is right 64 or 65 ? 
thanks very much for any help ! 非常感谢！

I write the following testing code:
```c
int main(int argc, char* argv[]) {
    if (argc < 2) {
        return -1;
    }
    std::cout << "Load Model from " << argv[1] << std::endl;
    std::string engine_path(argv[1]);
    SuperPointTensorRT sp_trt(engine_path, "", "",  160, 120, 0.012, true); 
    std::cout << "Load Model success" << std::endl << " Loading image " << argv[2] << std::endl;
```
`SuperPointTensorRT` is override class of `TensorRTInferenceGeneric`
the TensorRTInferenceGeneric code is as following, which is for any help.
```c
using namespace nvinfer1;
uint64_t get3DTensorVolume4(nvinfer1::Dims inputDims);

TensorRTInferenceGeneric::TensorRTInferenceGeneric(std::string input_blob_name, int _width, int _height):
    m_InputBlobName(input_blob_name), width(_width), height(_height){

}

void TensorRTInferenceGeneric::init(const std::string & engine_path) {

    m_Engine = loadTRTEngine(engine_path, nullptr, m_Logger);
    assert(m_Engine != nullptr);
    
    m_Context = m_Engine->createExecutionContext();
	assert(m_Context != nullptr);

    for (unsigned int i = 0; i < m_Engine->getNbBindings(); i ++ ) {
        std::string name(m_Engine->getBindingName(i));
        std::cout  << "TensorRT binding index " << i << " name " << name << std::endl;
    }

	m_InputBindingIndex = m_Engine->getBindingIndex(m_InputBlobName.c_str());
	assert(m_InputBindingIndex != -1);
    std::cout << "MaxBatchSize" << m_Engine->getMaxBatchSize() << std::endl;
	assert(m_BatchSize <= static_cast<uint32_t>(m_Engine->getMaxBatchSize()));
	allocateBuffers();
	NV_CUDA_CHECK(cudaStreamCreate(&m_CudaStream));
	assert(verifyEngine());

    std::cout << "TensorRT workspace " << m_Engine->getWorkspaceSize () /1024.0/1024.0 << "mb" << std::endl;
}

void TensorRTInferenceGeneric::doInference(const cv::Mat & input) {
    // assert(input.channels() == 1 && "Only support 1 channel now");
    TicToc inference;
    //This function is very slow event on i7, we need to optimize it
    //But not now.
    if (input.channels() == 1) {
        doInference(input.data, 1);
    } else {
        cv::Mat bgr[3];
        cv::split(input, bgr);
        static float * data_buf = new float[3*input.rows*input.cols];
        memcpy(data_buf, bgr[2].data, input.rows*input.cols*sizeof(float));
        memcpy(data_buf+input.rows*input.cols, bgr[1].data, input.rows*input.cols*sizeof(float));
        memcpy(data_buf+input.rows*input.cols*2, bgr[0].data, input.rows*input.cols*sizeof(float));
        doInference((unsigned char*)data_buf, 1);
    }
    //printf("doInference %fms\n", inference.toc());
}


void TensorRTInferenceGeneric::doInference(const unsigned char* input, const uint32_t batchSize)
{
	//Timer timer;
    assert(batchSize <= m_BatchSize && "Image batch size exceeds TRT engines batch size");
    NV_CUDA_CHECK(cudaMemcpyAsync(m_DeviceBuffers.at(m_InputBindingIndex), input,
                                  batchSize * m_InputSize * sizeof(float), cudaMemcpyHostToDevice,
                                  m_CudaStream));
	
    m_Context->enqueue(batchSize, m_DeviceBuffers.data(), m_CudaStream, nullptr);
    for (auto& tensor : m_OutputTensors)
    {
        NV_CUDA_CHECK(cudaMemcpyAsync(tensor.hostBuffer, m_DeviceBuffers.at(tensor.bindingIndex),
                                      batchSize * tensor.volume * sizeof(float),
                                      cudaMemcpyDeviceToHost, m_CudaStream));
    }
    cudaStreamSynchronize(m_CudaStream);
//	timer.out("inference");
}

bool TensorRTInferenceGeneric::verifyEngine()
{
    assert((m_Engine->getNbBindings() == (1 + m_OutputTensors.size())
            && "Binding info doesn't match between cfg and engine file \n"));

    for (auto tensor : m_OutputTensors)
    {
        assert(!strcmp(m_Engine->getBindingName(tensor.bindingIndex), tensor.blobName.c_str())
               && "Blobs names dont match between cfg and engine file \n");
        // std::cout << get3DTensorVolume4(m_Engine->getBindingDimensions(tensor.bindingIndex)) <<":" << tensor.volume << std::endl;
        assert(get3DTensorVolume4(m_Engine->getBindingDimensions(tensor.bindingIndex))
                   == tensor.volume
               && "Tensor volumes dont match between cfg and engine file \n");
    }

    assert(m_Engine->bindingIsInput(m_InputBindingIndex) && "Incorrect input binding index \n");
    assert(m_Engine->getBindingName(m_InputBindingIndex) == m_InputBlobName
           && "Input blob name doesn't match between config and engine file");
    assert(get3DTensorVolume4(m_Engine->getBindingDimensions(m_InputBindingIndex)) == m_InputSize);
    return true;
}

void TensorRTInferenceGeneric::allocateBuffers()
{
    m_DeviceBuffers.resize(m_Engine->getNbBindings(), nullptr);
    assert(m_InputBindingIndex != -1 && "Invalid input binding index");
    NV_CUDA_CHECK(cudaMalloc(&m_DeviceBuffers.at(m_InputBindingIndex),
                             m_BatchSize * m_InputSize * sizeof(float)));

    for (auto& tensor : m_OutputTensors)
    {
        tensor.bindingIndex = m_Engine->getBindingIndex(tensor.blobName.c_str());
        std::cout << "Tensor" << tensor.blobName.c_str() << " bind to " << tensor.bindingIndex 
                << " dim " << m_Engine->getBindingDimensions(tensor.bindingIndex).d[0]
                << " " << m_Engine->getBindingDimensions(tensor.bindingIndex).d[1]
                << " " << m_Engine->getBindingDimensions(tensor.bindingIndex).d[2]
                << " " << m_Engine->getBindingDimensions(tensor.bindingIndex).d[3] << std::endl;
        assert((tensor.bindingIndex != -1) && "Invalid output binding index");
        NV_CUDA_CHECK(cudaMalloc(&m_DeviceBuffers.at(tensor.bindingIndex),
                                 m_BatchSize * tensor.volume * sizeof(float)));
        NV_CUDA_CHECK(
            cudaMallocHost(&tensor.hostBuffer, tensor.volume * m_BatchSize * sizeof(float)));
    }
}


uint64_t get3DTensorVolume4(nvinfer1::Dims inputDims)
{
    int ret = 1;
    for (int i = 0; i < inputDims.nbDims; i ++) {
        ret = ret * inputDims.d[i];
    }
    return ret;
}
```

## my output
```sh
Load Model from /home/wzy/vins_ws/src/super-glue-pretrained-network-cius/models/weights/supernet_160_120.engine
Trying to init TRT engine of SuperPointTensorRT/home/wzy/vins_ws/src/super-glue-pretrained-network-cius/models/weights/supernet_160_120.engine
Loading TRT Engine...
Loading Complete!
TensorRT binding index 0 name data
TensorRT binding index 1 name semi
TensorRT binding index 2 name desc
MaxBatchSize1
Tensorsemi bind to 1 dim 65 15 20 0
Tensordesc bind to 2 dim 256 15 20 0
name:semi
inputDims.nbDims: 3
inputDims.d[i]: 65
inputDims.d[i]: 15
inputDims.d[i]: 20
19500:19200
name:desc
inputDims.nbDims: 3
inputDims.d[i]: 256
inputDims.d[i]: 15
inputDims.d[i]: 20
76800:76800
```

**Comment by myboyhood** [comment]
thank you，I will this script a few days later and give feedback soon

**Comment by myboyhood** [comment]
@xiang-wuu I tried this script, by
```
python demo_superpoint.py assets/nyu_snippet.mp4 --cuda --weights_path /home/zph/projects/tensorrtx/superpoint/build/supernet.engine
```
get the problem when `build_engine`, the output is as following. I do not know how to debug this ? Thank you very much !!
```
Namespace(H=120, W=160, camid=0, conf_thresh=0.015, cuda=True, display_scale=2, img_glob='*.png', input='assets/nyu_snippet.mp4', max_length=5, min_length=2, nms_dist=4, nn_thresh=0.7, no_display=False, show_extra=False, skip=1, waitkey=1, weights_path='/home/zph/projects/tensorrtx/superpoint/build/supernet.engine', write=False, write_dir='tracker_outputs/')
==> Processing Video Input.
==> Loading pre-trained network.
infer using tensorrt
Reading engine from file /home/zph/projects/tensorrtx/superpoint/build/supernet.engine
[02/08/2023-10:59:44] [TRT] [W] CUDA initialization failure with error: 35
Traceback (most recent call last):
  File "demo_superpoint.py", line 424, in <module>
    cudas=opt.cuda)
  File "/home/zph/projects/SuperPointPretrainedNetwork/model.py", line 115, in __init__
    self.engine, self.context = build_engine(weights_path)
  File "/home/zph/projects/SuperPointPretrainedNetwork/trt_infer.py", line 16, in build_engine
    with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
TypeError: pybind11::init(): factory function returned nullptr
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
[1]    22747 abort (core dumped)  python demo_superpoint.py assets/nyu_snippet.mp4 --cuda --weights_path
```

**Comment by myboyhood** [comment]
@xiang-wuu thank you, 
I try the script and it can works, Now I change my env to `cuda-11-6` and `TesnorRT-8.5`. Maybe my env is the big problem before.
