### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'

### ISSUE THREAD

**Issue by thariqkhalid** [wang-xinyu/tensorrtx#128]
@wang-xinyu I was trying to create the TensorRT model for a custom model built on top of yolov5s. But I'm getting the below error for the pretrained model itself. 

`python gen_wts.py 
`
for yolov5s pretrained model

```
Traceback (most recent call last):
  File "gen_wts.py", line 12, in <module>
    f.write('{}\n'.format(len(model.state_dict().keys())))
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 900, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 900, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 900, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 1 more time]
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 897, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _save_to_state_dict
    if buf is not None and name not in self._non_persistent_buffers_set:
  File "/home/thariqnx/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'
```

What could i be missing ? Please help

**Comment by wang-xinyu** [comment]
what's the pytorch version? and did you modify the `gen_wts.py`.

**Comment by thariqkhalid** [comment]
thanks for the reply.
pytorch version is 1.6.0. 
`gen_wts.py` has not been modified. it's still like 
```
import torch
import struct
from utils.torch_utils import select_device

# Initialize
device = select_device('cpu')
# Load model
model = torch.load('weights/yolov5s.pt', map_location=device)['model'].float()  # load to FP32
model.to(device).eval()

f = open('yolov5s.wts', 'w')
f.write('{}\n'.format(len(model.state_dict().keys())))
for k, v in model.state_dict().items():
    vr = v.reshape(-1).cpu().numpy()
    f.write('{} {} '.format(k, len(vr)))
    for vv in vr:
        f.write(' ')
        f.write(struct.pack('>f',float(vv)).hex())
    f.write('\n')

```

**Comment by wang-xinyu** [comment]
are you using the latest yolov5s.pt? which updated on Jul 29, 2020

**Comment by thariqkhalid** [comment]
Thanks a lot @wang-xinyu . i downloaded the latest yolov5s.pt . And the conversion was succesful!
