### ISSUE TITLE
yolov5_seg_trt.py not working when batch size 2 or more

### ISSUE THREAD

**Issue by dinobei** [wang-xinyu/tensorrtx#1293]
## Env
- RTX3090
- Ubuntu20.04
- Cuda 11.3
- TensorRT 8.5.3.1

## About this repo
yolov5-v7.0

## Your problem

When the batch size is set to 2 or more, the `yolov5_seg_trt.py` error occurs.

```
# in yolov5/src/config.h
...
constexpr static int kBatchSize = 2;
...
```

- what is your command? `python3 yolov5_seg_trt.py`
- what's your output?
```
...
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov5_seg_trt.py", line 478, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image(self.image_path_batch))
  File "yolov5_seg_trt.py", line 181, in infer
    result_boxes, result_scores, result_classid, result_proto_coef = self.post_process(
  File "yolov5_seg_trt.py", line 312, in post_process
    pred = np.reshape(output_boxes[1:], (-1, self.det_row_output_length))[:num, :]
  File "<__array_function__ internals>", line 180, in reshape
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 76001 into shape (70)
```

**Comment by wang-xinyu** [comment]
Did you rebuild the code and .engine after changing the batchsize?

**Comment by dinobei** [comment]
@wang-xinyu 
Yes, absolutely. Rebuilt and tested.

**Comment by wang-xinyu** [comment]
Also need to re-serialize the trt engine.
