### ISSUE TITLE
Yolov8 batch problem

### ISSUE THREAD

**Issue by spacewalk01** [wang-xinyu/tensorrtx#1334]
## Env

- GPU RTX2080.
- OS,  Win10, etc.
- Cuda version 11
- TensorRT version 8

## About this repo

- which branch/tag/commit are you using? latest (master)
- which model? yolov8?

## Your problem

yolov8 version batch inference is not working. When batch size equals to 1, it works well but when I set batch size to 4, only the first image in the batch is processed, and rest of them are not being processed.

**Comment by wang-xinyu** [comment]
@lindsayshuo please take a look.

**Comment by lindsayshuo** [comment]
> 
Which post-processing method are you using? GPU post-processing or CPU post-processing

**Comment by spacewalk01** [comment]
Tried both but didn't work

**Comment by Ittya12345** [comment]
i got the same progrem , when using my own model ,transform from onnx .this is the problem.
[07/22/2023-22:53:18] [TRT] [I] [MemUsageChange] Init CUDA: CPU +329, GPU +0, now: CPU 367, GPU 484 (MiB)
[07/22/2023-22:53:18] [TRT] [I] Loaded engine size: 15 MiB
[07/22/2023-22:53:19] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.5 but loaded cuBLAS/cuBLASLt 11.4.1
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +399, GPU +168, now: CPU 790, GPU 668 (MiB)
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +156, GPU +172, now: CPU 946, GPU 840 (MiB)
[07/22/2023-22:53:19] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.1.1
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +14, now: CPU 0, GPU 14 (MiB)
[07/22/2023-22:53:19] [TRT] [W] TensorRT was linked against cuBLAS/cuBLASLt 11.6.5 but loaded cuBLAS/cuBLASLt 11.4.1
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 930, GPU 832 (MiB)
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 930, GPU 840 (MiB)
[07/22/2023-22:53:19] [TRT] [W] TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.1.1
[07/22/2023-22:53:19] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +15, now: CPU 0, GPU 29 (MiB)
bingding: images (1, 3, 480, 480)
bingding: output0 (1, 16, 4725)
batch size is 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 399, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image_zeros())
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_trt.py", line 384, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
  File "yolov8_trt.py", line 179, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range

**Comment by wang-xinyu** [comment]
@Ittya12345 Have you tried the c++ executable?

**Comment by lindsayshuo** [comment]
> @Ittya12345 Have you tried the c++ executable?

The engine generated from Onnx  and the Wts engine is different ,they have different output dims

**Comment by Ittya12345** [comment]
> @Ittya12345 Have you tried the c++ executable?

 I have tired cpp ，but my model is the same as yolov8n, but have different classifies such as 5 ， so my model can not be build model.engone for model.WTS , so I use onnx to engine ，however , the cpp and Python applications both can not run the engine file , I find my problem in Python code . the engine can be load successful ly , but the output of boxx  point and the number of category is over 300 or negative number .

**Comment by Ittya12345** [comment]
> 

I solve the problem by add the classifies to 80 . I add 75 other classifies but my dataset don't have it . but it have a problem , which make the function very slow. so I use it on NX board. only have 20fps . the parameters is too many to have a variety.

**Comment by lindsayshuo** [comment]
> I solve the problem by add the classifies to 80 . I add 75 other classifies but my dataset don't have it . but it have a problem , which make the function very slow. so I use it on NX board. only have 20fps . the parameters is too many to have a variety.

please try the newest commit, there was a bug for yolov8n.

**Comment by mztony** [comment]
> > I solve the problem by add the classifies to 80 . I add 75 other classifies but my dataset don't have it . but it have a problem , which make the function very slow. so I use it on NX board. only have 20fps . the parameters is too many to have a variety.
> 
> please try the newest commit, there was a bug for yolov8n.

sorry to bother, do u fix the problem to use multiple batches in GPU post processing ? i am trying to modified your code and add nms-cuda in yolov5. For single batch in nms-cuda it works well , but for multiple batches haven't success yet.
