### ISSUE TITLE
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by twd19990423** [wang-xinyu/tensorrtx#1501]
## Env

- GPU, 1080ti
- OS, e.g. Ubuntu18.04
- Cuda version 11.1
- TensorRT 8.2.5.1

The reasoning of the C version is normal，However, the python version will report this error。
The same device and TensorRT version are the same。Looking forward to hearing from you。Thanks

Traceback (most recent call last):
  File "/mnt/workspace/rv2d/acus_workspace/twd_workspace/tensorrtx-master/yolov8/yolov8_seg_trt.py", line 15, in <module>
    import tensorrt as trt
  File "/mnt/workspace/rv2d/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorrt/__init__.py", line 67, in <module>
    from .tensorrt import *
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory

**Comment by wang-xinyu** [comment]
The tensorrt-py and the tensorrt c++ need to be the same version.

**Comment by twd19990423** [comment]
<img width="386" alt="微信截图_20240426175320" src="https://github.com/wang-xinyu/tensorrtx/assets/111330377/7c66c54c-ee87-4ac1-996f-acf3fb21aa39">
<img width="1003" alt="微信截图_20240426175404" src="https://github.com/wang-xinyu/tensorrtx/assets/111330377/65729828-808f-4201-a467-8eed2c2e878b">
Thanks for your reply。
My C version is consistent with the Python version of Tensorrt, is this the version you said is consistent Or did I misunderstand

**Comment by wang-xinyu** [comment]
Set LD_LIBRARY_PATH, put the lib path of tensorrt into this ENV.
