### ISSUE TITLE
Python error about mobilenetV3

### ISSUE THREAD

**Issue by angryhen** [wang-xinyu/tensorrtx#200]
I refer to yolov5_trt.py of yoloV5 and try to implement the compiled mobilenetV3_large.engine and libh_sigmoid.so through python. The main modifications are as follows:
CMakeLists.txt
```txt

cmake_minimum_required(VERSION 2.6)

project(mobilenetv3)

add_definitions(-std=c++11)

option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)

find_package(CUDA REQUIRED)

set(CUDA_NVCC_PLAGS ${CUDA_NVCC_PLAGS};-std=c++11;-g;-G;-gencode;arch=compute_30;code=sm_30;)

include_directories(${PROJECT_SOURCE_DIR}/include)
if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    message("embed_platform on")
    include_directories(/usr/local/cuda/targets/aarch64-linux/include)
    link_directories(/usr/local/cuda/targets/aarch64-linux/lib)
else()
    message("embed_platform off")
    include_directories(/usr/local/cuda/include)
    link_directories(/usr/local/cuda/lib64)
endif()

cuda_add_library(h_sigmoid SHARED ${PROJECT_SOURCE_DIR}/h_sigmoid.cu)

add_executable(mobilenetv3 ${PROJECT_SOURCE_DIR}/h_sigmoidplugin.cpp ${PROJECT_SOURCE_DIR}/mobilenet_v3.cpp)
target_link_libraries(mobilenetv3 nvinfer)
target_link_libraries(mobilenetv3 cudart)
target_link_libraries(mobilenetv3 h_sigmoid)

add_definitions(-O2 -pthread)
```
The python file is as follows
```python
 PLUGIN_LIBRARY ='tensorrtx/mobilenetv3/build/libh_sigmoid.so'
 ctypes.CDLL(PLUGIN_LIBRARY)
 engine_file_path = "tensorrtx/mobilenetv3/build/mobilenetv3_large.engine"
```
Till i got the following error
```
[TensorRT] ERROR: deserializationUtils.cpp (567)-Serialization Error in load: 0 (Serialized engine contains plugin, but no plugin factory was provided. To deserialize an engine without a factory, please use IPluginV2 instead.)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "/home/du/Desktop/my_project/trt_project/tensorrtx/infere_engine.py", line 171, in <module>
    yolov5_warpper = effTRT(engine_file_path)
  File "/home/du/Desktop/my_project/trt_project/tensorrtx/infere_engine.py", line 40, in __init__
    context = engine.create_execution_context()
AttributeError:'NoneType' object has no attribute'create_execution_context'
-------------------------------------------------- -----------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------- -----------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------- -----------------

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by wang-xinyu** [comment]
[TensorRT] ERROR: deserializationUtils.cpp (567)-Serialization Error in load: 0 (Serialized engine contains plugin, but no plugin factory was provided. To deserialize an engine without a factory, please use IPluginV2 instead.)

The mobilenetv3 was using trt4 api,  you need set the pluginfactory in python,

or adapt the mobilenetv3 to trt7 api, and use REGISTER_PLUGIN instead of pluginfactory.

you can refer to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/migrating_from_tensorrt_4_to_7.md

**Comment by angryhen** [comment]
@wang-xinyu 
Thanks very much, it turns out this is a version problem. I found that in yoloV5, x* hsigmoid was used to replace hswish, and I successfully ran my model with this

**Comment by wang-xinyu** [comment]
You can submit a PR for  mobilenetv3 migrated to trt7,   If you are interested.
