### ISSUE TITLE
[gen_wts.py] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ontheway16** [wang-xinyu/tensorrtx#202]
Hello, I am trying to convert a custom YOLOv4 weight file, but its throwing the following error;
```
$ python gen_wts.py yolov4.weights
Traceback (most recent call last):
  File "gen_wts.py", line 6, in <module>
    model = Darknet('yolov4_custom.cfg', (608, 608))
  File "/home/qgs/yolov3/models.py", line 231, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "/home/qgs/yolov3/utils/parse_config.py", line 25, in parse_model_cfg
    key, val = line.split("=")
ValueError: not enough values to unpack (expected 2, got 1)
```

Any ideas ?

**Comment by wang-xinyu** [comment]
This error is parsing model cfg failed.   You need first make sure your model can run with https://github.com/ultralytics/yolov3.
