### ISSUE TITLE
yolov5_trt

### ISSUE THREAD

**Issue by alicera** [wang-xinyu/tensorrtx#323]
command:
yolov5_trt.py 

ERROR:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "yolov5_trt.py", line 288, in run
    self.func(*self.args)
  File "yolov5_trt.py", line 144, in infer
    output, origin_h, origin_w
  File "yolov5_trt.py", line 257, in post_process
    pred = np.reshape(output[1:], (-1, 5))[:num, :]
  File "<__array_function__ internals>", line 6, in reshape
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 115199 into shape (6)

**Comment by alicera** [comment]
请问从1: 开始是因为num_boxes吧 ，所以num_boxes 是3吧？为何要这样
而且6 是由[cx,cy,w,h,conf,cls_id]组成， 所以假设有10类cls_id就为0~9，这样每个anchor不就只能预测一类

  pred = np.reshape(output[1:], (-1, 6))[:num, :]
