### ISSUE TITLE
yolov5s int8 calibration fail

### ISSUE THREAD

**Issue by yueyihua** [wang-xinyu/tensorrtx#519]
## Env

- GPU, Xavier NX
- OS, Ubuntu18.04
- Cuda 10.2
- TensorRT 7.1

## About this repo
Master branch, yolov5s model

## Your problem
Starting program: /home/yyh/Work/yolov5/build/yolov5 -s ../best.wts ../yolov5s_best_int8.engine s
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f99cbb9c0 (LWP 18507)]
Loading weights: ../best.wts
Your platform support int8: true
Building engine, please wait for a while...
reading calib cache: int8calib.table
[New Thread 0x7f911ee9c0 (LWP 18508)]
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

Thread 1 "yolov5" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000007fa9c108d4 in __GI_abort () at abort.c:79
#2  0x0000007fa9ea610c in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#3  0x0000007fa9ea3c54 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#4  0x0000007fa9ea3ca0 in std::terminate() () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#5  0x0000007fa9ea3f68 in __cxa_throw () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#6  0x0000007fa9ecc868 in std::__throw_out_of_range(char const*) () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#7  0x0000007fab031ed0 in ?? () from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#8  0x0000007fab02d8ac in nvinfer1::builder::applyPerTensorCalibration(nvinfer1::builder::Graph const&, nvinfer1::NetworkBuildConfig&, nvinfer1::NetworkQuantizationConfig const&, std::unordered_map<std::string, float, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, float> > >&) () from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#9  0x0000007fab0ada94 in nvinfer1::builder::buildEngine(nvinfer1::NetworkBuildConfig&, nvinfer1::NetworkQuantizationConfig const&, nvinfer1::builder::EngineBuildContext const&, nvinfer1::Network const&) ()
   from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#10 0x0000007fab0c3a50 in nvinfer1::builder::Builder::buildInternal(nvinfer1::NetworkBuildConfig&, nvinfer1::NetworkQuantizationConfig const&, nvinfer1::builder::EngineBuildContext const&, nvinfer1::Network const&) ()
   from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#11 0x0000007fab0c4a48 in nvinfer1::builder::Builder::buildEngineWithConfig(nvinfer1::INetworkDefinition&, nvinfer1::IBuilderConfig&) () from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#12 0x000000555556ad6c in build_engine (maxBatchSize=0, builder=0x5566c35730, config=0x555623a8b0, dt=<optimized out>, gd=<optimized out>, gw=<optimized out>, wts_name=...) at /home/yyh/Work/yolov5/yolov5.cpp:115
#13 0x000000555556d41c in APIToModel (maxBatchSize=1, modelStream=0x7fffffe9d0, is_p6=@0x7fffffe967: false, gd=@0x7fffffe968: 0.330000013, gw=@0x7fffffe96c: 0.5, wts_name="../best.wts") at /home/yyh/Work/yolov5/yolov5.cpp:245
#14 0x0000005555561a1c in main (argc=5, argv=0x7fffffef38) at /home/yyh/Work/yolov5/yolov5.cpp:320
(gdb) q

**Comment by yueyihua** [comment]
calibration data dir not correct，sorry
