### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'to'`

### ISSUE THREAD

**Issue by amirxu** [wang-xinyu/tensorrtx#611]
## Env

- GPU, Xavier NX
- OS, Ubuntu16.04
- Cuda version，10.2

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
`nx@nx-desktop:~/Pytorch-UNet/utils$ python3 gen_wts.py `
- what's your output?
`cuda device count:  1
Traceback (most recent call last):
  File "gen_wts.py", line 36, in <module>
    main()
  File "gen_wts.py", line 11, in main
    net = net.to('cuda:0')
AttributeError: 'collections.OrderedDict' object has no attribute 'to'`
- what output do you expect?
如何解决这个报错？

**Comment by dickang** [comment]
请问你解决了这个问题吗？我也遇到了这个问题！

**Comment by wang-xinyu** [comment]
注意下pytorch版本，可能新版本已经没有to.('cuda:0')这个写法

**Comment by dickang** [comment]
请问这个项目中unet部署你用的是哪个版本的pytorch呢？

**Comment by wang-xinyu** [comment]
试试1.3
