### ISSUE TITLE
Some tactics do not have sufficient workspace memory to run.

### ISSUE THREAD

**Issue by namdvt** [wang-xinyu/tensorrtx#855]
Hello, I am new to TensorRT. I was running the lenet example in the TensorRT Python API and faced this issue:

[TensorRT] INFO: 
[TensorRT] INFO: --------------- Layers running on DLA: 
[TensorRT] INFO: 
[TensorRT] INFO: --------------- Layers running on GPU: 
[TensorRT] INFO: (Unnamed Layer* 0) [Convolution] + (Unnamed Layer* 1) [Activation], (Unnamed Layer* 2) [Pooling], (Unnamed Layer* 3) [Convolution] + (Unnamed Layer* 4) [Activation], (Unnamed Layer* 5) [Pooling], (Unnamed Layer* 6) [Fully Connected] + (Unnamed Layer* 7) [Activation], 2-layer MLP: (Unnamed Layer* 8) [Fully Connected] + (Unnamed Layer* 9) [Activation] -> (Unnamed Layer* 10) [Fully Connected], (Unnamed Layer* 11) [Softmax], 
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] ERROR: Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
[TensorRT] ERROR: ../builder/tacticOptimizer.cpp (1715) - TRTInternal Error in computeCosts: 0 (Could not find any implementation for node 2-layer MLP: (Unnamed Layer* 8) [Fully Connected] + (Unnamed Layer* 9) [Activation] -> (Unnamed Layer* 10) [Fully Connected].)
[TensorRT] ERROR: ../builder/tacticOptimizer.cpp (1715) - TRTInternal Error in computeCosts: 0 (Could not find any implementation for node 2-layer MLP: (Unnamed Layer* 8) [Fully Connected] + (Unnamed Layer* 9) [Activation] -> (Unnamed Layer* 10) [Fully Connected].)
Traceback (most recent call last):
  File "lenet.py", line 171, in <module>
    APIToModel(1)
  File "lenet.py", line 135, in APIToModel
    assert engine
AssertionError

I am using tensorRT 7.1.3.0 on Jetson device. Many thanks.

**Comment by wang-xinyu** [comment]
can you try the cpp one?

**Comment by namdvt** [comment]
yes the cpp one works perfectly.

**Comment by wang-xinyu** [comment]
Probably bugs in tensorrt py package for  jetson.

@irvingzhang0512 any ideas?
